CREATE TABLE A (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	a TEXT
);

CREATE TABLE B (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	b TEXT,
	_composition_attribut TEXT
);

CREATE TABLE C (
	id INTEGER PRIMARY KEY AUTOINCREMENT
);

